version: '3'
services:
  postgres:
    image: postgres:alpine3.18
    hostname: postgres
    ports:
      - 5432:5432
    container_name: db
    env_file:
      - .env
  scraper:
    build: .
    volumes:
      - .:/app
    container_name: scraper
    # restart: always
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
    env_file:
      - .env